import java.util.*;

public class Program4 {
  public static void main(String[] args) {
    Scanner scan = new Scanner(System.in);
    
    String input = scan.nextLine();
    toBraille(input);
  }
  private static void toBraille(String in) {
    for (int i = 0; i < in.length(); i++) {
      String[] print = braille(Character.toLowerCase(in.charAt(i)));
      System.out.print(print[0]);
    }
    System.out.println();
    for (int i = 0; i < in.length(); i++) {
      String[] print = braille(Character.toLowerCase(in.charAt(i)));
      System.out.print(print[1]);
    }
    System.out.println();
    for (int i = 0; i < in.length(); i++) {
      String[] print = braille(Character.toLowerCase(in.charAt(i)));
      System.out.print(print[2]);
    }
    System.out.println();
    for (int i = 0; i < in.length(); i++) {
      String[] print = braille(Character.toLowerCase(in.charAt(i)));
      System.out.print(print[3]);
    }
  }
  private static String[] braille(char in) {
    String[] a = new String[4];
    a[0] = "a  ";
    a[1] = ". |";
    a[2] = "  |";
    a[3] = "  |";
    String[] b = new String[4];
    b[0] = "b  ";
    b[1] = ". |";
    b[2] = ". |";
    b[3] = "  |";
    String[] c = new String[4];
    c[0] = "c  ";
    c[1] = "..|";
    c[2] = "  |";
    c[3] = "  |";
    String[] d = new String[4];
    d[0] = "d  ";
    d[1] = "..|";
    d[2] = " .|";
    d[3] = "  |";
    String[] e = new String[4];
    e[0] = "e  ";
    e[1] = ". |";
    e[2] = " .|";
    e[3] = "  |";
    String[] f = new String[4];
    f[0] = "f  ";
    f[1] = "..|";
    f[2] = ". |";
    f[3] = "  |";
    String[] g = new String[4];
    g[0] = "g  ";
    g[1] = "..|";
    g[2] = "..|";
    g[3] = "  |";
    String[] h = new String[4];
    h[0] = "h  ";
    h[1] = ". |";
    h[2] = "..|";
    h[3] = "  |";
    String[] i = new String[4];
    i[0] = "i  ";
    i[1] = " .|";
    i[2] = ". |";
    i[3] = "  |";
    String[] j = new String[4];
    j[0] = "j  ";
    j[1] = " .|";
    j[2] = "..|";
    j[3] = "  |";
    String[] k = new String[4];
    k[0] = "k  ";
    k[1] = ". |";
    k[2] = "  |";
    k[3] = ". |";
    String[] l = new String[4];
    l[0] = "l  ";
    l[1] = ". |";
    l[2] = ". |";
    l[3] = ". |";
    String[] m = new String[4];
    m[0] = "m  ";
    m[1] = "..|";
    m[2] = "  |";
    m[3] = ". |";
    String[] n = new String[4];
    n[0] = "n  ";
    n[1] = "..|";
    n[2] = " .|";
    n[3] = ". |";
    String[] o = new String[4];
    o[0] = "o  ";
    o[1] = ". |";
    o[2] = " .|";
    o[3] = ". |";
    String[] p = new String[4];
    p[0] = "p  ";
    p[1] = "..|";
    p[2] = ". |";
    p[3] = ". |";
    String[] q = new String[4];
    q[0] = "q  ";
    q[1] = "..|";
    q[2] = "..|";
    q[3] = ". |";
    String[] r = new String[4];
    r[0] = "r  ";
    r[1] = ". |";
    r[2] = "..|";
    r[3] = ". |";
    String[] s = new String[4];
    s[0] = "s  ";
    s[1] = " .|";
    s[2] = ". |";
    s[3] = ". |";
    String[] t = new String[4];
    t[0] = "t  ";
    t[1] = " .|";
    t[2] = "..|";
    t[3] = ". |";
    String[] u = new String[4];
    u[0] = "u  ";
    u[1] = ". |";
    u[2] = "  |";
    u[3] = "..|";
    String[] v = new String[4];
    v[0] = "v  ";
    v[1] = ". |";
    v[2] = ". |";
    v[3] = "..|";
    String[] w = new String[4];
    w[0] = "w  ";
    w[1] = " .|";
    w[2] = "..|";
    w[3] = " .|";
    String[] x = new String[4];
    x[0] = "x  ";
    x[1] = "..|";
    x[2] = "  |";
    x[3] = "..|";
    String[] y = new String[4];
    y[0] = "y  ";
    y[1] = "..|";
    y[2] = " .|";
    y[3] = "..|";
    String[] z = new String[4];
    z[0] = "z  ";
    z[1] = ". |";
    z[2] = " .|";
    z[3] = "..|";
    String[] space = new String[4];
    space[0] = "   ";
    space[1] = "  |";
    space[2] = "  |";
    space[3] = "  |";
    String[] one = new String[4];
    one[0] = "1  ";
    one[1] = ". |";
    one[2] = "  |";
    one[3] = "  |";
    String[] two = new String[4];
    two[0] = "2  ";
    two[1] = ". |";
    two[2] = ". |";
    two[3] = "  |";
    String[] three = new String[4];
    three[0] = "3  ";
    three[1] = "..|";
    three[2] = "  |";
    three[3] = "  |";
    String[] four = new String[4];
    four[0] = "4  ";
    four[1] = "..|";
    four[2] = " .|";
    four[3] = "  |";
    String[] five = new String[4];
    five[0] = "5  ";
    five[1] = ". |";
    five[2] = " .|";
    five[3] = "  |";
    String[] six = new String[4];
    six[0] = "6  ";
    six[1] = "..|";
    six[2] = ". |";
    six[3] = "  |";
    String[] seven = new String[4];
    seven[0] = "7  ";
    seven[1] = "..|";
    seven[2] = "..|";
    seven[3] = "  |";
    String[] eight = new String[4];
    eight[0] = "8  ";
    eight[1] = ". |";
    eight[2] = "..|";
    eight[3] = "  |";
    String[] nine = new String[4];
    nine[0] = "9  ";
    nine[1] = " .|";
    nine[2] = ". |";
    nine[3] = "  |";
    String[] zero = new String[4];
    zero[0] = "0  ";
    zero[1] = " .|";
    zero[2] = "..|";
    zero[3] = "  |";

    if (in == 'a') return a;
    else if (in == 'b') return b;
    else if (in == 'c') return c;
    else if (in == 'd') return d;
    else if (in == 'e') return e;
    else if (in == 'f') return f;
    else if (in == 'g') return g;
    else if (in == 'h') return h;
    else if (in == 'i') return i;
    else if (in == 'j') return j;
    else if (in == 'k') return k;
    else if (in == 'l') return l;
    else if (in == 'm') return m;
    else if (in == 'n') return n;
    else if (in == 'o') return o;
    else if (in == 'p') return p;
    else if (in == 'q') return q;
    else if (in == 'r') return r;
    else if (in == 's') return s;
    else if (in == 't') return t;
    else if (in == 'u') return u;
    else if (in == 'v') return v;
    else if (in == 'w') return w;
    else if (in == 'x') return x;
    else if (in == 'y') return y;
    else if (in == 'z') return z;
    else if (in == '1') return one;
    else if (in == '2') return two;
    else if (in == '3') return three;
    else if (in == '4') return four;
    else if (in == '5') return five;
    else if (in == '6') return six;
    else if (in == '7') return seven;
    else if (in == '8') return eight;
    else if (in == '9') return nine;
    else if (in == '0') return zero;
    else return space;
  }
}
